const files=["emergencies","tooth-pain","crowns-restorative","implants","cosmetic","preventive","florida-costs-insurance","south-florida-resources"];
const labels={all:"All topics",emergencies:"Emergencies","tooth-pain":"Tooth pain","crowns-restorative":"Crowns & restorative",implants:"Implants",cosmetic:"Cosmetic",preventive:"Prevention","florida-costs-insurance":"Costs & insurance","south-florida-resources":"South Florida resources"};
const list=document.querySelector("#answer-list"),filters=document.querySelector("#filters"),search=document.querySelector("#search"),count=document.querySelector("#result-count"),empty=document.querySelector("#empty-state");
let entries=[],topic=new URLSearchParams(location.search).get("topic")||"all";
const escapeHTML=value=>String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function renderFilters(){filters.innerHTML=["all",...files].map(key=>`<button class="filter" type="button" data-topic="${key}" aria-pressed="${topic===key}">${labels[key]}</button>`).join("")}
function articleBrief(item){return `${item.question}\n\nLocal angle: Answer this evergreen question for Miami and Pinecrest patients in clear, reassuring language. Avoid diagnosing the reader, guarantees, invented prices, and claims that cannot be sourced.\n\nKey answer: ${item.answer}\n\nRecommended next step: ${item.nextStep}\n\nRelated search language: ${item.tags.join(", ")}\n\nMedical note: Educational information only; a dentist must examine the patient to diagnose or recommend treatment.`}
function render(){const term=search.value.trim().toLowerCase();const shown=entries.filter(item=>(topic==="all"||item.topic===topic)&&(!term||[item.question,item.answer,item.nextStep,...item.tags,"Miami Pinecrest South Florida dentist near me how much does it cost what should I do"].join(" ").toLowerCase().includes(term)));count.textContent=`${shown.length} ${shown.length===1?"evergreen topic":"evergreen topics"}`;empty.hidden=shown.length!==0;list.hidden=shown.length===0;list.innerHTML=shown.map(item=>`<details class="answer-card" id="${escapeHTML(item.id)}"><summary>${escapeHTML(item.question)}</summary><div class="answer-body"><p>${escapeHTML(item.answer)}</p><p class="next-step"><strong>What to do next:</strong> ${escapeHTML(item.nextStep)}</p><p><strong>Article angle:</strong> Explain this question for Miami and Pinecrest readers, then cover warning signs, options to discuss with a dentist, and practical next steps.</p>${item.sources.length?`<p class="sources"><strong>Learn more:</strong> ${item.sources.map(s=>`<a href="${escapeHTML(s.url)}">${escapeHTML(s.label)}</a>`).join(" · ")}</p>`:""}<button class="copy-brief button" type="button" data-id="${escapeHTML(item.id)}">Copy article brief</button><div class="meta"><span class="urgency urgency-${item.urgency}">${item.urgency} guidance</span><span>Reviewed ${escapeHTML(item.reviewed)}</span></div></div></details>`).join("")}
filters.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;topic=button.dataset.topic;const url=new URL(location);topic==="all"?url.searchParams.delete("topic"):url.searchParams.set("topic",topic);history.replaceState({},"",url);renderFilters();render()});
search.addEventListener("input",render);document.querySelector("#clear-search").addEventListener("click",()=>{search.value="";topic="all";renderFilters();render();search.focus()});document.addEventListener("keydown",event=>{if(event.key==="/"&&!/input|textarea/i.test(document.activeElement.tagName)){event.preventDefault();search.focus()}});
const dialog=document.querySelector("#disclaimer-dialog");document.querySelectorAll("[data-dialog-open]").forEach(button=>button.addEventListener("click",()=>dialog.showModal()));document.querySelectorAll("[data-dialog-close]").forEach(button=>button.addEventListener("click",()=>dialog.close()));
list.addEventListener("click",async event=>{const button=event.target.closest(".copy-brief");if(!button)return;const item=entries.find(entry=>entry.id===button.dataset.id);if(!item)return;try{await navigator.clipboard.writeText(articleBrief(item));button.textContent="Copied";setTimeout(()=>button.textContent="Copy article brief",1500)}catch{button.textContent="Select and copy unavailable"}});
try{const datasets=files.map(file=>window.DENTAL_ANSWER_DATA[file]||[]);entries=datasets.flatMap((items,index)=>items.map(item=>({...item,topic:files[index]})));renderFilters();render()}catch(error){count.textContent="Answers unavailable";list.innerHTML=`<p role="alert">The offline answer library could not be loaded.</p>`;console.error(error)}
